name: Tests
run-name: ${{ github.actor }} is starting the tests action.
on: [push]
jobs:
  Static-Analysis:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event. By branch- ${{ github.ref }} , repo- ${{ github.repository }} ."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Install ShellCheck
        run: |
          sudo apt update
          sudo apt install shellcheck
          shellcheck -V
          # wget -q -o shellcheck-v0.10.0.linux.x86_64.tar.xz https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz
          # sudo apt install xz-utils -y
          # ls
          # echo "--"
          # tar -xJf shellcheck-v0.10.0.linux.x86_64.tar.xz
          # ls
          # cd shellcheck-v0.10.0/
          # cp shellcheck /usr/local/bin
      - name: ShellCheck - a lint checker for shell scripts
        run: |
          cd "${{ github.workspace }}"
          ./tests/linux-shellcheck.sh
      - run: echo "Tests check successful!🍏"
          